export let actions={ //异步处理VUEX
  mapData(store,data){
    store.commit("mapData",data)
  },
  multiActivityId(store,data){
    store.commit("multiActivityId",data)
  },
  payId(store,data){
    store.commit("payId",data)
  },
  tabbarAarrIndex(store,data){
    store.commit("tabbarAarrIndex",data)
  },
  headerIndex(store,data){
    store.commit("headerIndex",data)
  },
  homePageIndex(store,data){
    store.commit("homePageIndex",data)
  },
  loadingFalse(store,data){
    store.commit("loadingFalse",data)
  },
  FollowScrollTop(store,data){
    store.commit("FollowScrollTop",data)
  },
  WEATHERVANEScrollTop(store,data){
    store.commit("WEATHERVANEScrollTop",data)
  },
  resource_poolScrollTop(store,data){
    store.commit("resource_poolScrollTop",data)
  },
  design_offeeScrollTop(store,data){
    store.commit("design_offeeScrollTop",data)
  },
};
