
export let mutations = {
  mapData(state,data){
    state.mapData=data;
  },
  multiActivityId(state,data){
    state.multiActivityId=data;
  },
  payId(state,data){
    state.payId=data;
  },
  tabbarAarrIndex(state,data){
    state.tabbarAarrIndex=data;
  },
  headerIndex(state,data){
    state.headerIndex=data;
  },
  homePageIndex(state,data){
    state.homePageIndex=data;
  },
  loadingFalse(state,data){
    state.loadingFalse=data;
  },
  FollowScrollTop(state,data){
    state.FollowScrollTop=data;
  },
  WEATHERVANEScrollTop(state,data){
    state.WEATHERVANEScrollTop=data;
  },
  resource_poolScrollTop(state,data){
    state.resource_poolScrollTop=data;
  },
  design_offeeScrollTop(state,data){
    state.design_offeeScrollTop=data;
  },
}
